openapi: 3.0.3
info:
  title: 醃造所專題 API
  version: 1.0.0
  description: |
    **Supabase 前端設定方式**：
      - supabaseUrl: `https://kficknhvujgeaooqxiif.supabase.co`<br><br>
      - supabaseAnonKey:`找俐涵拿`
tags:
- name: 產品資訊
- name: 會員資訊
- name: 優惠券
  description: 別用，還沒好！！！
- name: 購物車
  description: 別用，還沒好！！！
- name: 首頁
  description: 顧客好評
servers:
  - url: https://kficknhvujgeaooqxiif.supabase.co/rest/v1
paths:
  /products:
    get:
      tags:
        - 產品資訊
      summary: 取得所有商品（含變體）
      description: >
        可以帶 query `select=*,variants:product_variants(id,name,price,stock)` 
        取得產品及所有規格資訊
      parameters:
        - in: query
          name: select
          required: false
          schema:
            type: string
          example: "*,variants:product_variants(id,name,price,stock)"
          description: "Supabase REST API 用法，選擇回傳欄位"
      responses:
        '200':
          description: 商品列表（包含變體）
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    # post:
    #   summary: 新增商品
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/ProductInput'
    #   responses:
    #     '201':
    #       description: 新增成功
  /products/{id}:
    get:
      tags:
        - 產品資訊
      summary: 取得單一商品（含變體）
      description: >
        可以帶 query `select=*,variants:product_variants(id,name,price,stock)` 
        取得單一商品及其規格資訊
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: 商品 ID
        - in: query
          name: select
          required: false
          schema:
            type: string
          example: "*,variants:product_variants(id,name,price,stock)"
          description: "Supabase REST API 用法，選擇回傳欄位"
      responses:
        '200':
          description: 單一商品（包含變體）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    # patch:
    #   summary: 修改商品
    #   parameters:
    #     - in: path
    #       name: id
    #       required: true
    #       schema:
    #         type: string
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/ProductInput'
    #   responses:
    #     '200':
    #       description: 修改成功
    # delete:
    #   summary: 刪除商品
    #   parameters:
    #     - in: path
    #       name: id
    #       required: true
    #       schema:
    #         type: string
    #   responses:
    #     '204':
    #       description: 刪除成功

  # /product_variants:
  #   get:
  #     summary: 取得商品變體
  #     responses:
  #       '200':
  #         description: 變體列表
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: '#/components/schemas/ProductVariant'
    # post:
    #   summary: 新增商品變體
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/ProductVariantInput'
    #   responses:
    #     '201':
    #       description: 新增成功

  /carts:
    get:
      tags:
        - 購物車
      summary: 取得使用者購物車
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 購物車列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartItem'
    post:
      tags:
        - 購物車
      summary: 新增購物車項目
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartItemInput'
      responses:
        '201':
          description: 新增成功
    delete:
      tags:
        - 購物車
      summary: 清空購物車
      parameters:
        - in: query
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 已清空

  /coupons:
    get:
      tags:
        - 優惠券
      summary: 取得可用優惠券
      responses:
        '200':
          description: 優惠券列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Coupon'
    post:
      tags:
        - 優惠券
      summary: 套用優惠券
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                coupon_code:
                  type: string
      responses:
        '200':
          description: 回傳折扣金額
          content:
            application/json:
              schema:
                type: object
                properties:
                  discount_amount:
                    type: integer

  /customer_reviews:
    get:
      tags:
        - 首頁
      summary: 取得顧客評論
      responses:
        '200':
          description: 顧客評論列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerReview'
  /users/{id}:
    get:
      tags:
        - 會員資訊
      summary: 取得使用者資訊
      parameters:
        - name: id
          in: path
          description: 使用者ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 使用者資訊
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    patch:
      tags:
        - 會員資訊
      summary: 更新使用者資料（可部分更新）
      parameters:
        - name: id
          in: path
          description: 使用者ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'


components:
  schemas:
    Product:
      type: object
      properties:
        id: 
           type: string
           example: "23d5e2f5-1bfb-4a3e-9348-dbc1c2a23b59"
        title:
          type: string
          example: "檸檬老醬蘿蔔"
        category:
          type: string 
          example: "熱門商品"
        description:
          type: string
          example: "嚴選爽脆白蘿蔔，融合新鮮檸檬的清香與老薑的暖香，經細心醃漬，使酸、甜、微辣層次分明。入口先是檸檬的清爽酸甜，隨後薑香緩緩散開，最後是蘿蔔的脆口回甘，適合佐餐或作為開胃小菜。"
        image_url:
          type: string
          example: "https://kficknhvujgeaooqxiif.supabase.co/storage/v1/object/public/products/ningmeng_laojiang_luobo.png"
        images_url: 
          type: array
          items: 
             type: string 
          example:
            - "https://kficknhvujgeaooqxiif.supabase.co/storage/v1/object/public/products/ningmeng_laojiang_luobo_bg.png"
        origin: 
          type: object
          additionalProperties:
            type: string
          example:
            白蘿蔔: "台東"
            檸檬: "屏東"
            老薑: "雲林"
        price: 
           type: integer 
           description: 商品最低售價（顯示用，實際以 variant.price 為準）
           example: 300
        num: 
          type: integer 
          description: 商品頁預設選擇數量
          example: 1
        summary: 
           type: string 
           example: "爽脆白蘿蔔，檸檬清香交織老薑暖韻，酸甜清爽、開胃耐吃。"
        ingredients: 
           type: string 
           example: "白蘿蔔、新鮮檸檬汁、老薑、冰糖、食鹽、醋（釀造醋)"
        variants:
          type: array
          description: 商品的所有規格
          items:
            $ref: '#/components/schemas/Variant'
    Variant:
      type: object
      properties:
        id:
          type: string
          example: "3dc847e3-af2c-4e52-8ad5-35ff1f34f90e"
        name:
          type: string
          example: "500ml 慢醃大罐"
        price:
          type: integer
          example: 500
        stock:
          type: integer
          description: 剩餘庫存數量（前端可依此判斷是否顯示庫存充足／不足）
          example: 8
    # ProductInput:
    #   type: object
    #   properties:
    #     title: { type: string }
    #     category: { type: string }
    #     description: { type: string }
    #     image_url: { type: string }
    #     images_url: 
    #       type: array
    #       items: { type: string }
    #     origin: 
    #       type: object
    #     default_variant_id: { type: string }
    #     selected_variant_id: { type: string }
    #     price: { type: integer }
    #     num: { type: integer }
    #     is_enabled: { type: boolean }
    #     summary: { type: string }
    #     ingredients: { type: string }
    ProductVariant:
      type: object
      properties:
        id: 
           type: string 
           format: uuid
        product_id: { type: string }
        name: { type: string }
        size: { type: string }
        price: { type: integer }
        unit: { type: string }
        stock: { type: integer }
    # ProductVariantInput:
    #   type: object
    #   properties:
    #     product_id: { type: string }
    #     name: { type: string }
    #     size: { type: string }
    #     price: { type: integer }
    #     unit: { type: string }
    #     stock: { type: integer }
    CartItem:
      type: object
      properties:
        cart_id: { type: string }
        user_id: { type: string }
        product: { $ref: '#/components/schemas/Product' }
        variant: { $ref: '#/components/schemas/ProductVariant' }
        quantity: { type: integer }
        subtotal: { type: integer }
    CartItemInput:
      type: object
      properties:
        user_id: { type: string }
        product_id: { type: string }
        variant_id: { type: string }
        quantity: { type: integer }
    Coupon:
      type: object
      properties:
        id: { type: string }
        code: { type: string }
        title: { type: string }
        description: { type: string }
        discount_amount: { type: integer }
        min_purchase: { type: integer }
        start_date: { type: string, format: date }
        end_date: { type: string, format: date }
        is_active: { type: boolean }
    CustomerReview:
      type: object
      properties:
        id: { type: string }
        name:
          type: string 
          example: "吳伯伯"
        occupation:
          type: string
          example: "銀髮養生族"
        photo_url: { type: string }
        comment:
          type: string
          example: "我跟太太年紀大了，醫生叫我們少油少鹽，但常常吃得太清淡，連飯都吞不下去。兒子有天帶回你們的醃洋蔥，說我們可以試試看，結果我們吃了一整碗粥都覺得有味道了。太太還特地寫紙條貼冰箱：『記得補貨』。我們現在會一起挑味道，每一款都不錯吃，也健康。"
    User:
      type: object
      description: 使用者完整資訊（包含系統欄位 id）
      properties:
        id: { type: string }
        email: 
          type: string 
          example: "2006@yen.made.com"
        full_name: 
          type: string 
          example: "王小俐"
        phone: 
          type: string 
          example: "0911222333"
        address:
          type: string 
          example: "台中市西屯區六角路66號"
        title:
          type: string
          example: "女士"
        birthday: 
          type: string
          format: date
          example: "1999-06-06"
    UserInput:
      type: object
      description: 更新使用者資料用，可部分更新，未填欄位不會被修改
      properties:
        email:
          type: string
          nullable: true
          example: "2006@yen.made.com"
        full_name:
          type: string
          nullable: true
          example: "王小俐"
        phone:
          type: string
          nullable: true
          example: "0911222333"
        address:
          type: string
          nullable: true
          example: "台中市西屯區六角路66號"
        title:
          type: string
          nullable: true
          example: "女士"
        birthday:
          type: string
          format: date
          example: "1999-06-06"
