openapi: 3.0.3
info:
  title: 醃造所專題 API
  version: 1.0.0
  description: |
    **Supabase 前端設定方式**：
      - supabaseUrl: `https://kficknhvujgeaooqxiif.supabase.co`
      - supabaseAnonKey: `找俐涵拿`
tags:
  - name: Auth
    description: 註冊與登入 API
  - name: 產品資訊
  - name: orders
  - name: 購物車
  - name: 優惠券
  - name: 會員資訊
  - name: 首頁
    description: 顧客好評
servers:
  - url: https://kficknhvujgeaooqxiif.supabase.co/rest/v1

paths:

  # -------------------------
  # Auth API
  # -------------------------
  /auth/signup:
    post:
      tags: [Auth]
      summary: 註冊新帳號（Email + Password）
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, example: "user@example.com" }
                password: { type: string, example: "yourPassword123" }
      responses:
        '200':
          description: 註冊成功，回傳使用者資訊
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /auth/signin:
    post:
      tags: [Auth]
      summary: 使用 Email + Password 登入
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string, example: "user@example.com" }
                password: { type: string, example: "yourPassword123" }
      responses:
        '200':
          description: 登入成功，回傳 session 與使用者資訊
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  # -------------------------
  # 產品 API
  # -------------------------
  /products:
    get:
      tags: [產品資訊]
      summary: 取得所有商品（含變體）
      responses:
        '200':
          description: 商品列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /products/{id}:
    get:
      tags: [產品資訊]
      summary: 取得單一商品（含變體）
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: 單一商品
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  # -------------------------
  # 訂單 API
  # -------------------------
  # /orders:
  #   post:
  #     tags: [orders]
  #     summary: 結帳，建立新訂單
  #     description: |
  #       將使用者購物車內的商品結算，建立一筆訂單與對應 order_items，並清空購物車。
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             properties:
  #               user_id: { type: string, description: "使用者 ID" }
  #               coupon_id: { type: string, nullable: true, description: "優惠券 ID，可選" }
  #               recipient_name: { type: string }
  #               recipient_phone: { type: string }
  #               recipient_email: { type: string }
  #               recipient_address: { type: string }
  #               invoice_type:
  #                 type: string
  #                 enum: ['寄送發票', '通用載具']
  #               note: { type: string, nullable: true }
  #     responses:
  #       '201':
  #         description: 訂單建立成功
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/Order'

  #   get:
  #     tags: [orders]
  #     summary: 取得使用者所有訂單
  #     parameters:
  #       - in: query
  #         name: user_id
  #         required: true
  #         schema: { type: string }
  #     responses:
  #       '200':
  #         description: 使用者訂單列表
  #         content:
  #           application/json:
  #             schema:
  #               type: array
  #               items:
  #                 $ref: '#/components/schemas/Order'

  # /orders/{id}:
  #   get:
  #     tags: [orders]
  #     summary: 查詢單筆訂單
  #     parameters:
  #       - in: path
  #         name: id
  #         required: true
  #         schema: { type: string }
  #     responses:
  #       '200':
  #         description: 單筆訂單明細
  #         content:
  #           application/json:
  #             schema:
  #               $ref: '#/components/schemas/OrderDetailed'

  # -------------------------
  # 購物車 API
  # -------------------------
  /carts:
    get:
      tags: [購物車]
      summary: 取得使用者購物車列表
      parameters:
        - in: query
          name: user_id
          required: true
          schema: { type: string }
      responses:
        '200':
          description: 使用者購物車列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CartItem'

    post:
      tags: [購物車]
      summary: 新增購物車項目
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CartItemInput'
      responses:
        '201':
          description: 新增成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItem'

    delete:
      tags: [購物車]
      summary: 清空使用者購物車
      parameters:
        - in: query
          name: user_id
          required: true
          schema: { type: string }
      responses:
        '204':
          description: 已清空購物車

  /carts/{cart_id}:
    patch:
      tags: [購物車]
      summary: 更新購物車商品數量
      parameters:
        - in: path
          name: cart_id
          required: true
          schema: { type: string }
          description: 購物車項目 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity: { type: integer, example: 3 }
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CartItem'

    delete:
      tags: [購物車]
      summary: 刪除購物車單一商品
      parameters:
        - in: path
          name: cart_id
          required: true
          schema: { type: string }
          description: 購物車項目 ID
      responses:
        '204':
          description: 刪除成功

  # -------------------------
  # 優惠券 API
  # -------------------------
  /coupons:
    get:
      tags: [優惠券]
      summary: 取得可用優惠券
      responses:
        '200':
          description: 優惠券列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Coupon'

    post:
      tags: [優惠券]
      summary: 套用優惠券
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id: { type: string }
                coupon_code: { type: string }
      responses:
        '200':
          description: 回傳折扣金額
          content:
            application/json:
              schema:
                type: object
                properties:
                  discount_amount: { type: integer }

  # -------------------------
  # 顧客評論 API
  # -------------------------
  /customer_reviews:
    get:
      tags: [首頁]
      summary: 取得顧客評論
      responses:
        '200':
          description: 顧客評論列表
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CustomerReview'

  # -------------------------
  # 會員資訊 API
  # -------------------------
  /users/{id}:
    get:
      tags: [會員資訊]
      summary: 取得使用者資訊
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: 使用者資訊
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    patch:
      tags: [會員資訊]
      summary: 更新使用者資料（可部分更新）
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        session:
          type: object
          properties:
            access_token: { type: string }
            refresh_token: { type: string }
            expires_in: { type: integer }

    User:
      type: object
      properties:
        id: { type: string }
        email: { type: string }
        full_name: { type: string }
        phone: { type: string }
        address: { type: string }
        title: { type: string }
        birthday: { type: string, format: date }

    UserInput:
      type: object
      properties:
        email: { type: string, nullable: true }
        full_name: { type: string, nullable: true }
        phone: { type: string, nullable: true }
        address: { type: string, nullable: true }
        title: { type: string, nullable: true }
        birthday: { type: string, format: date }

    Product:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        category: { type: string }
        description: { type: string }
        image_url: { type: string }
        images_url:
          type: array
          items: { type: string }
        origin:
          type: object
          additionalProperties: { type: string }
        price: { type: integer }
        num: { type: integer }
        summary: { type: string }
        ingredients: { type: string }
        variants:
          type: array
          items:
            $ref: '#/components/schemas/Variant'

    Variant:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        price: { type: integer }
        stock: { type: integer }

  

    CartItem:
      type: object
      properties:
        cart_id: { type: string }
        user_id: { type: string }
        product: { $ref: '#/components/schemas/Product' }
        variant: { $ref: '#/components/schemas/Variant' }
        quantity: { type: integer }
        subtotal:
          type: integer
          description: 單項金額 = variant.price * quantity

    CartItemInput:
      type: object
      properties:
        user_id: { type: string }
        product_id: { type: string }
        variant_id: { type: string }
        quantity: { type: integer }

    Coupon:
      type: object
      properties:
        id: { type: string }
        code: { type: string }
        title: { type: string }
        description: { type: string }
        discount_amount: { type: integer }
        min_purchase: { type: integer }
        start_date: { type: string, format: date }
        end_date: { type: string, format: date }
        is_active: { type: boolean }

    CustomerReview:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        occupation: { type: string }
        photo_url: { type: string }
        comment: { type: string }

  # properties:
  #       id: { type: string }
  #       order_no: { type: string, description: "訂單編號，例如 YM-20260124-AB12" }
  #       user_id: { type: string }
  #       coupon_id: { type: string, nullable: true }
  #       recipient_name: { type: string }
  #       recipient_phone: { type: string }
  #       recipient_email: { type: string }
  #       recipient_address: { type: string }
  #       invoice_type:
  #         type: string
  #         enum: ['寄送發票', '通用載具']
  #       note: { type: string, nullable: true }
  #       subtotal: { type: integer }
  #       shipping_fee: { type: integer }
  #       discount_amount: { type: integer }
  #       total_amount: { type: integer }
  #       status:
  #         type: string
  #         enum: ['訂單已成立','訂單已付款','配送中','已完成']
  #       created_at: { type: string, format: date-time }
  #       updated_at: { type: string, format: date-time }

  # OrderItem:
  #   type: object
  #   properties:
  #     id: { type: string }
  #     product_id: { type: string }
  #     variant_id: { type: string }
  #     product_title: { type: string }
  #     variant_name: { type: string }
  #     variant_size: { type: string, nullable: true }
  #     unit_price: { type: integer }
  #     quantity: { type: integer }
  #     subtotal: { type: integer }

  # OrderDetailed:
  #   type: object
  #   properties:
  #     order:
  #       $ref: '#/components/schemas/Order'
  #     items:
  #       type: array
  #       items:
  #         $ref: '#/components/schemas/OrderItem'